#############################################################################
# Makefile for building: eggibault
# Generated by qmake (1.07a) (Qt 3.3.4) on: Sun Apr  2 14:22:41 2006
# Project:  eggibault.pro
# Template: app
# Command: $(QMAKE) -o Makefile eggibault.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fomit-frame-pointer -march=i586 -mtune=pentiumpro  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fomit-frame-pointer -march=i586 -mtune=pentiumpro  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib/qt3/mkspecs/default -I. -I$(QTDIR)/include -I.ui/ -I. -I.moc/
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = .obj/

####### Files

HEADERS = 
SOURCES = main.cpp
OBJECTS = .obj/main.o \
		.obj/mainfrm.o
FORMS = mainfrm.ui
UICDECLS = .ui/mainfrm.h
UICIMPLS = .ui/mainfrm.cpp
SRCMOC   = .moc/moc_mainfrm.cpp
OBJMOC = .obj/moc_mainfrm.o
DIST	   = eggibault.pro
QMAKE_TARGET = eggibault
DESTDIR  = 
TARGET   = eggibault

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: eggibault.pro  /usr/lib/qt3/mkspecs/default/qmake.conf /usr/lib/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile eggibault.pro
qmake: 
	@$(QMAKE) -o Makefile eggibault.pro

dist: 
	@mkdir -p .obj/eggibault && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .obj/eggibault/ && $(COPY_FILE) --parents mainfrm.ui.h .obj/eggibault/ && ( cd `dirname .obj/eggibault` && $(TAR) eggibault.tar eggibault && $(GZIP) eggibault.tar ) && $(MOVE) `dirname .obj/eggibault`/eggibault.tar.gz . && $(DEL_FILE) -r .obj/eggibault

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

.obj/main.o: main.cpp .ui/mainfrm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.ui/mainfrm.h: mainfrm.ui 
	$(UIC) mainfrm.ui -o .ui/mainfrm.h

.ui/mainfrm.cpp: .ui/mainfrm.h mainfrm.ui mainfrm.ui.h 
	$(UIC) mainfrm.ui -i mainfrm.h -o .ui/mainfrm.cpp

.obj/mainfrm.o: .ui/mainfrm.cpp mainfrm.ui.h \
		.ui/mainfrm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mainfrm.o .ui/mainfrm.cpp

.obj/moc_mainfrm.o: .moc/moc_mainfrm.cpp  .ui/mainfrm.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mainfrm.o .moc/moc_mainfrm.cpp

.moc/moc_mainfrm.cpp: $(MOC) .ui/mainfrm.h
	$(MOC) .ui/mainfrm.h -o .moc/moc_mainfrm.cpp

####### Install

install:  

uninstall:  

